name: OCaml CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: dune build
    # - name: Tidy
    #   run: rebar3 update
    #        rebar3 lint
    # - name: Format
    #   run: rebar3 steamroll
    # - name: Run tests
    #   run: rebar3 do eunit, ct