name: OCaml CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  run:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.x
    - name: Build
      run: |
       opam install dune
       eval $(opam config env)
       opam install -t . --deps-only
       opam install ounit2.2.2.6
       opam install ocamlformat
       opam exec -- dune build

   run:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Linting
      run:  opam exec -- dune fmt

   run:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: opam exec -- dune runtest