name: OCaml CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  run:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: ${{ '4.06.2' }}
    - name: Dependencies
      run: opam install -t . --deps-only
    - name: Build
      run: opam exec -- dune build